add implementation for tasmota fw
3mdeb/sonoff-rest-api pull request #2
Opened 2024-02-15 19:28 UTC by macpijan

2024-04-22 12:39 UTC, pkubaj commented on README
> +  [ESPHome firmware](https://esphome.io/devices/sonoff.html)
Trailing whitespace.

2024-04-22 12:41 UTC, pkubaj commented
Is it intentional that there is supposed to be `sonoff-api-esphome.robot` and `sonoff-esphome-api.robot` with the same content but slightly different keyword names?

2024-04-22 12:42 UTC, pkubaj commented
Also, as I understand it, setting which firmware is to be used is by creating `sonoff-api.robot` symlink, is that right?

2024-04-22 12:50 UTC, pkubaj requested changes

2024-04-22 12:50 UTC, pkubaj commented on README
> +  [ESPHome firmware](https://esphome.io/devices/sonoff.html)
Trailing whitespace.

2024-04-22 13:32 UTC, macpijan commented
> Also, as I understand it, setting which firmware is to be used is by creating sonoff-api.robot symlink, is that right?

Currently it is, since it was simply the easiest.

We are using tasmota only now, so should not be a prolbem.

2024-04-22 13:33 UTC, macpijan commented
> Is it intentional that there is sonoff-api-esphome.robot and sonoff-esphome-api.robot with the same content but slightly different keyword names?

Yes it was, especially when we have not migrated yet. But now we have tasmota only FW in lab.

2024-04-24 07:35 UTC, macpijan commented on README
> +  [ESPHome firmware](https://esphome.io/devices/sonoff.html)
Fixed in: 0783b18032d405a556ec684b0b9287b0f9254919

2024-04-24 07:35 UTC, macpijan commented
Clarified usage in: 0783b18032d405a556ec684b0b9287b0f9254919

Merging since we only use Tasmota right now.

2024-04-24 07:35 UTC, merged